FROM nvidia/cuda:12.6.1-devel-ubuntu24.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=8.0"

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    clang \
    cmake \
    gdb \
    git \
    wget

# Install doxygen and graphviz
RUN apt-get install -y doxygen graphviz 